### ISSUE TITLE
ModuleNotFoundError: No module named 'server'

### ISSUE THREAD

**Issue by zdizou** [Atrides/eth-proxy#37]
hello
can someone help me pls 

`py eth-proxy.py
Traceback (most recent call last):
  File "C:\Users\oumish\Desktop\Nouveau dossier (2)\eth-proxy\eth-proxy.py", line 9, in <module>
    from stratum import settings
  File "C:\Users\oumish\Desktop\Nouveau dossier (2)\eth-proxy\stratum\__init__.py", line 1, in <module>
    from server.py import setup
ModuleNotFoundError: No module named 'server'`

thanks

**Comment by huykent** [comment]
> hello
> can someone help me pls
> 
> `py eth-proxy.py Traceback (most recent call last): File "C:\Users\oumish\Desktop\Nouveau dossier (2)\eth-proxy\eth-proxy.py", line 9, in <module> from stratum import settings File "C:\Users\oumish\Desktop\Nouveau dossier (2)\eth-proxy\stratum\__init__.py", line 1, in <module> from server.py import setup ModuleNotFoundError: No module named 'server'`
> 
> thanks

use ubuntu 18.04 and python-twisted + zope.interface

**Comment by wuping1984** [comment]
aparently you need old python version, like 2.7.3. Just use conda to create it.
